"""Bounded native IR execution and a hardened, explicitly authorized OCI boundary.

A Python subprocess is not advertised as a security sandbox. Main campaigns
must use a locally present, digest-pinned OCI image or a separately qualified
remote isolation service. No arbitrary shell or Python generated by a model is
executed. OCI reduces exposure; its kernel/runtime remain part of the TCB.
"""
from __future__ import annotations

import math
import os
import selectors
import signal
import subprocess
import sys
import time
import uuid
from dataclasses import dataclass

from .core import Cost, Refused, canonical, fields, integer, numeric, parse, require
from .language import compile_program


@dataclass(frozen=True)
class SandboxConfig:
    mode: str = "native"
    image: str | None = None
    runtime: str = "/usr/bin/docker"
    memory_mb: int = 256
    cpus: float = 1.0
    pids: int = 32
    wall_seconds: float = 10.0
    output_bytes: int = 1024 * 1024

    def __post_init__(self):
        require(self.mode in {"native", "oci"}, "unsupported sandbox mode")
        integer(self.memory_mb, 64, 8192)
        numeric(self.cpus, 0.1, 16)
        integer(self.pids, 8, 256)
        numeric(self.wall_seconds, 0.1, 3600)
        integer(self.output_bytes, 1024, 4 * 1024 * 1024)
        if self.mode == "oci":
            require(type(self.image) is str and "@sha256:" in self.image, "OCI image must be digest-pinned")
            suffix = self.image.rsplit("@sha256:", 1)[1]
            require(len(suffix) == 64 and all(c in "0123456789abcdef" for c in suffix), "invalid OCI digest")
            require(os.path.isabs(self.runtime), "runtime path must be operator-pinned and absolute")


def bounded_process(argv: list[str], request: bytes, *, timeout: float, output_limit: int) -> bytes:
    """No shell; bounded stdin/stdout/stderr; kill the owned process group on failure."""
    require(len(request) <= 4 * 1024 * 1024, "worker input bound")
    env = {"PATH": "/usr/local/bin:/usr/bin:/bin", "LANG": "C.UTF-8", "HOME": "/nonexistent"}
    process = subprocess.Popen(argv, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                               start_new_session=True, env=env)
    selector = selectors.DefaultSelector()
    deadline = time.monotonic() + timeout
    stdout, stderr = bytearray(), bytearray()
    offset = 0
    try:
        for stream, mode in ((process.stdin, selectors.EVENT_WRITE), (process.stdout, selectors.EVENT_READ),
                             (process.stderr, selectors.EVENT_READ)):
            os.set_blocking(stream.fileno(), False)
            selector.register(stream, mode)
        while selector.get_map():
            remaining = deadline - time.monotonic()
            require(remaining > 0, "sandbox wall timeout")
            for key, mask in selector.select(min(0.1, remaining)):
                if mask & selectors.EVENT_WRITE:
                    try:
                        offset += os.write(key.fd, request[offset:offset + 65536])
                    except BrokenPipeError:
                        offset = len(request)
                    if offset == len(request):
                        selector.unregister(key.fileobj)
                        key.fileobj.close()
                else:
                    chunk = os.read(key.fd, 65536)
                    if not chunk:
                        selector.unregister(key.fileobj)
                        key.fileobj.close()
                        continue
                    target = stdout if key.fileobj is process.stdout else stderr
                    target.extend(chunk)
                    require(len(stdout) + len(stderr) <= output_limit, "sandbox output bound")
        code = process.wait(timeout=max(0.001, deadline - time.monotonic()))
        require(code == 0, "sandbox failed; bounded diagnostics retained only in caller-owned failure record")
        return bytes(stdout)
    finally:
        if process.poll() is None:
            os.killpg(process.pid, signal.SIGKILL)
            process.wait()
        selector.close()
        for stream in (process.stdin, process.stdout, process.stderr):
            if not stream.closed:
                stream.close()


class Executor:
    def __init__(self, config: SandboxConfig, *, main: bool = False):
        require(not main or config.mode == "oci", "main qualification requires OCI isolation")
        self.config = config

    def batch(self, program: dict, inputs: list[dict]) -> tuple[list, Cost]:
        require(type(inputs) is list and 1 <= len(inputs) <= 64, "worker batch size must be 1..64")
        compile_program(program)  # Validate the closed language before dispatch, without executing it.
        request = {"schema": "substrate-worker-v2", "program": program, "inputs": inputs}
        started = time.perf_counter_ns()
        if self.config.mode == "native":
            response = execute_request(request)
        else:
            name = "substrate-" + uuid.uuid4().hex
            config = self.config
            argv = [config.runtime, "run", "--rm", "--pull=never", "--name", name, "-i", "--network=none",
                    "--read-only", "--cap-drop=ALL", "--security-opt=no-new-privileges", "--user=65534:65534",
                    f"--pids-limit={config.pids}", f"--memory={config.memory_mb}m", f"--memory-swap={config.memory_mb}m",
                    f"--cpus={config.cpus}", "--tmpfs=/tmp:rw,noexec,nosuid,nodev,size=8m", config.image,
                    "python", "-I", "-m", "substrate.sandbox"]
            try:
                response = parse(bounded_process(argv, canonical(request), timeout=config.wall_seconds,
                                                  output_limit=config.output_bytes))
            finally:
                # Killing the client alone need not terminate the daemon-owned container.
                try:
                    subprocess.run([config.runtime, "rm", "-f", name], stdin=subprocess.DEVNULL,
                                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=10, check=False)
                except (OSError, subprocess.TimeoutExpired):
                    raise Refused("container cleanup uncertain; quarantine worker host before continuing")
        fields(response, {"outputs", "execution_ns"})
        require(len(response["outputs"]) == len(inputs), "worker omitted outputs")
        integer(response["execution_ns"], 1)
        elapsed = max(1, time.perf_counter_ns() - started)
        # Amortized end-to-end wall time includes validation, launch and cleanup.
        return response["outputs"], Cost(elapsed_ns=math.ceil(elapsed / len(inputs)), source="batch-amortized-wall")


def execute_request(request: dict) -> dict:
    fields(request, {"schema", "program", "inputs"})
    require(request["schema"] == "substrate-worker-v2", "invalid worker schema")
    require(type(request["inputs"]) is list and 1 <= len(request["inputs"]) <= 64, "worker batch size bound")
    program = compile_program(request["program"])
    started = time.perf_counter_ns()
    outputs = [program.run(item) for item in request["inputs"]]
    return {"outputs": outputs, "execution_ns": max(1, time.perf_counter_ns() - started)}


def main() -> None:
    raw = sys.stdin.buffer.read(4 * 1024 * 1024 + 1)
    response = execute_request(parse(raw))
    sys.stdout.buffer.write(canonical(response))


if __name__ == "__main__":
    main()
