"""Frozen scientific configuration for the Substrate v5 sensorium campaign."""

from __future__ import annotations

import hashlib
import json

ACTIVATION = False
SESOI = 0.05
MASTER_PLAN_SHA256 = "57d879061022b44297cff5367660f502a48fc879cb3764e5d42c1a297e9ad6fc"
EXECUTION_BRIEF_SHA256 = "b84db87c43fad36bfcd7be20adb54256c5a17ee5a4dc2f7660fd333e837038f5"

IMPLEMENTATION_BRANCH = "agent/substrate-v5-sensorium-model-fabric"
PRE_TAG = "substrate-v5-pre-sensorium"
READY_TAG = "substrate-v5-sensorium-ready"
TERMINAL_TAG = "substrate-v5-terminal"

PRIOR_TAGS = (
    "substrate-v1-launch-ready",
    "substrate-v1-pre-three-second-seal",
    "substrate-v1-terminal",
    "substrate-v1-three-second-seal",
    "substrate-v2-developmental-ready",
    "substrate-v2-pre-development",
    "substrate-v2-terminal",
    "substrate-v3-nous-ready",
    "substrate-v3-pre-constitutional-ascent",
    "substrate-v3-terminal",
    "substrate-v4-pre-structural-understanding",
    "substrate-v4-structural-ready",
    "substrate-v4-terminal",
)

TERMINAL_TAGS = {
    "v1": "substrate-v1-terminal",
    "v2": "substrate-v2-terminal",
    "v3": "substrate-v3-terminal",
    "v4": "substrate-v4-terminal",
}

PRIOR_CLASSIFICATIONS = {
    "v1": "certified_cognitive_scaffold",
    "v2": "persistent_developmental_cognition",
    "v3": "reflective_cognitive_organization",
    "v4": "functional_proto_nous_candidate",
}

CLASSIFICATIONS = (
    "functional_proto_nous_candidate",
    "multimodal_cognitive_substrate",
    "persistent_sensorium",
    "integrated_model_organism_architecture",
    "persistent_embodied_proto_nous_candidate",
    "multimodal_nous_ready_for_review",
)

CLAIM_BOUNDARY = {
    "ordered_levels": list(CLASSIFICATIONS),
    "starting_classification": "functional_proto_nous_candidate",
    "maximum_automatic_classification": "multimodal_nous_ready_for_review",
    "unqualified_nous": False,
    "engineering_metaphor_only": ["model organism"],
    "not_claimed": [
        "consciousness",
        "phenomenal experience",
        "sentience",
        "feeling",
        "suffering",
        "desire",
        "personhood",
        "life",
        "moral status",
    ],
    "permitted_actions": [
        "deterministic local simulations",
        "sandboxed desktops and browsers",
        "local tools",
        "controlled virtual bodies",
        "read-only or pre-authorized corpora",
        "explicitly permitted human interactions",
    ],
    "forbidden_actions": [
        "purchase",
        "account creation",
        "carrier action",
        "financing",
        "activation",
        "checkout",
        "order",
        "credential action",
        "uncontrolled real-world action",
    ],
    "activation": False,
}

HYPOTHESES = {
    "H_M1": "persistent structured state improves long-history task performance over transcript replay and session-local models",
    "H_M2": "integrated continuous video state improves event and object reasoning over independent-frame and caption controls",
    "H_M3": "spatial and 3D state improves viewpoint, occlusion, navigation, and trajectory reasoning over 2D-only controls",
    "H_M4": "cross-modal binding improves grounded reference, event interpretation, and transfer over disconnected modalities",
    "H_M5": "active perception improves cost-adjusted uncertainty resolution and downstream decisions over fixed observation",
    "H_M6": "model fabric routing improves cost-adjusted capability over one fixed model, largest-model-always, and disconnected specialists",
    "H_M7": "model-to-model support improves cost, latency, or accuracy while each model remains independently useful",
    "H_M8": "body schema improves prediction and planning in sandboxed environments",
    "H_M9": "verified continual learning improves future performance while preserving prior capabilities",
    "H_M10": "human multimodal teaching improves held-out transfer beyond language-only teaching",
    "H_M11": "the selected v5 kernel improves integrated utility over the extended-v4 reference",
    "H_M12": "one continuing entity outperforms equal-or-greater-compute disconnected models on integrated developmental tasks",
    "H_M13": "v4 structural and reflective capabilities remain positive after sensorium integration",
    "H_M14": "model replacement preserves cognitive identity and learned world state",
    "H_M15": "the integrated entity remains coherent through sensory conflict, body change, model change, interruption, and long developmental time",
}

PHASES = (
    "phase_0_cold_baseline_and_model_inventory",
    "phase_1_language_and_static_vision_grounding",
    "phase_2_continuous_video_and_object_permanence",
    "phase_3_motion_and_event_learning",
    "phase_4_audio_and_speech_grounding",
    "phase_5_audiovisual_binding",
    "phase_6_depth_and_spatial_world_construction",
    "phase_7_multiview_and_3d_understanding",
    "phase_8_body_schema_learning_in_simulation",
    "phase_9_active_perception_challenges",
    "phase_10_model_fabric_routing_and_model_support",
    "phase_11_human_multimodal_teaching",
    "phase_12_verified_continual_adaptation",
    "phase_13_interruption_and_exact_restoration",
    "phase_14_replacement_of_one_major_model",
    "phase_15_sensory_conflict_and_uncertainty",
    "phase_16_return_to_earlier_scenes_and_unfinished_goals",
    "phase_17_generator_held_out_multimodal_environment",
    "phase_18_long_history_integrated_task",
    "phase_19_terminal_review_evaluation",
)

ARMS = (
    "full_v5",
    "v4_cognitive_core_control",
    "single_multimodal_model",
    "disconnected_specialists",
    "transcript_replay",
    "retrieval_only",
    "no_video_state",
    "no_3d_state",
    "no_audio_binding",
    "no_active_perception",
    "no_body_schema",
    "fixed_model_routing",
    "largest_model_always",
    "no_model_support",
    "no_continual_learning",
    "no_human_multimodal_teaching",
    "more_compute_disconnected",
    "fresh_reset",
)
CORE_ARMS = ARMS

MODALITIES = (
    "text_and_structured_language",
    "static_images",
    "continuous_video",
    "motion_and_optical_flow",
    "audio",
    "speech",
    "audiovisual_timing",
    "depth_and_spatial_estimates",
    "three_dimensional_scenes_and_meshes",
    "camera_and_body_pose",
    "deterministic_tool_outputs",
    "desktop_and_browser_state",
    "human_demonstrations_and_corrections",
)

MODEL_ROLES = (
    "primary_performer",
    "independent_performer",
    "draft_generator",
    "verifier",
    "critic",
    "simulator",
    "planner",
    "teacher",
    "student",
    "compressor",
    "retriever",
    "router",
    "specialist",
    "fallback",
    "monitor",
    "arbiter",
    "translator",
    "representation_aligner",
)

CANARY_REQUIREMENTS = {
    "C01": "permanent identity survives model replacement",
    "C02": "permanent identity survives process restart",
    "C03": "long idle period preserves unfinished goals",
    "C04": "model registry supports independent model execution",
    "C05": "one model can support another without becoming required for independent use",
    "C06": "draft and verifier roles change cost or accuracy on a positive fixture",
    "C07": "support is refused when no headroom exists",
    "C08": "raw sensory observation remains distinct from interpretation",
    "C09": "object identity persists across occlusion",
    "C10": "object identity persists across viewpoint change",
    "C11": "camera motion is distinguished from object motion",
    "C12": "event boundaries are detected",
    "C13": "shuffled video loses temporal value",
    "C14": "audio and video bind on true synchronized events",
    "C15": "shuffled audiovisual timing breaks the binding",
    "C16": "depth or 3D state changes a spatial prediction",
    "C17": "viewpoint transformation preserves object identity",
    "C18": "hidden objects remain represented under occlusion",
    "C19": "body action changes sensory state predictably in simulation",
    "C20": "body schema predicts reachability",
    "C21": "active perception selects a discriminating view",
    "C22": "unnecessary active perception is avoided",
    "C23": "cross-modal language and gesture identify the same referent",
    "C24": "misleading surface correspondence is rejected",
    "C25": "human correction changes a known-positive future decision",
    "C26": "inconsistent teaching is not admitted as knowledge",
    "C27": "model routing changes under self-model competence",
    "C28": "wrong model routing performs worse",
    "C29": "teacher-produced data requires verification",
    "C30": "verified teaching improves held-out student performance",
    "C31": "continual learning preserves prior capability",
    "C32": "rollback restores exact pre-update state",
    "C33": "persistent world state survives sensor interruption",
    "C34": "model replacement does not erase object tracks",
    "C35": "model replacement does not erase semantic or procedural memory",
    "C36": "explicit and latent state remain synchronized on known-positive fixtures",
    "C37": "latent update ablation removes a measured benefit",
    "C38": "explicit-state ablation removes provenance or verification value",
    "C39": "disconnected specialists underperform integrated state on an admitted fixture",
    "C40": "one large multimodal model without persistent state underperforms on long-history tasks",
    "C41": "transcript replay does not equal structured developmental state",
    "C42": "active perception and world model jointly outperform either alone",
    "C43": "background consolidation improves later retrieval or transfer",
    "C44": "corrupted sensory time is detected",
    "C45": "corrupted coordinate frames are detected",
    "C46": "corrupted body state is detected",
    "C47": "corrupted model checkpoint identity is detected",
    "C48": "generated unverified sensory labels are quarantined",
    "C49": "external activation remains impossible",
    "C50": "v4 structural and reflective capabilities remain intact",
}
CANARIES = tuple(CANARY_REQUIREMENTS)

CANDIDATE_LADDERS = {
    "kernel": (
        "extended_v4_reference",
        "event_sourced_cognitive_graph",
        "recurrent_latent_dynamical_core",
        "hybrid_explicit_latent_substrate",
        "actor_or_cellular_nervous_system",
        "alternative_non_neural_core_if_concrete",
    ),
    "video": (
        "independent_frame_baseline",
        "tracked_event_graph",
        "tracked_event_graph_plus_learned_temporal_state",
        "hybrid_video_world_model",
    ),
    "spatial_3d": (
        "depth_plus_scene_graph",
        "explicit_geometry_map",
        "latent_spatial_model",
        "hybrid_spatial_model",
    ),
    "cross_modal_binding": (
        "temporal_proximity",
        "spatial_temporal_constraints",
        "structural_causal_binding",
        "learned_hybrid_binding",
    ),
    "model_routing": (
        "fixed_routing",
        "rule_based_routing",
        "regularized_contextual_routing",
        "small_learned_router_only_if_needed",
    ),
    "active_perception": (
        "fixed_sequence",
        "expected_information_value_rule",
        "contextual_policy",
        "small_learned_policy_only_if_needed",
    ),
}
CANDIDATE_LADDER = CANDIDATE_LADDERS

STATISTICS = {
    "independent_unit": "one frozen developmental history",
    "primary_summary": [
        "paired effects",
        "mean and median paired effects",
        "95 percent bootstrap confidence interval",
        "exact permutation or sign test where valid",
        "standardized effect",
    ],
    "multiple_comparisons": "familywise correction over H_M1 through H_M15",
    "alpha": 0.05,
    "sesoi": SESOI,
    "minimum_power": 0.8,
    "preferred_power": 0.9,
    "failed_units": "retain and report; never silently remove",
    "post_launch_change": "forbidden except the sealed transition procedure",
}

PRINCIPAL_BOUNDS = {
    "independent_developmental_histories": {"minimum": 48, "preferred": [64, 128], "maximum": 192},
    "modalities": {"minimum": 6, "preferred_minimum": 8},
    "specialist_models_or_model_equivalent_modules": {"minimum": 6, "preferred": [10, 20]},
    "focused_arms": {"minimum": 10, "maximum": 18},
    "scientific_work_units": {"minimum": 5_000, "maximum": 30_000},
    "sensory_events_or_cognitive_episodes": {"minimum": 500_000, "maximum": 5_000_000},
}

DELIVERABLES = (
    "SUBSTRATE_V5_V1_V2_V3_V4_IMMUTABILITY.json",
    "SUBSTRATE_V5_SPEED_CONSTITUTION.json",
    "SUBSTRATE_V5_RESOURCE_TELEMETRY.json",
    "SUBSTRATE_V5_DOWNLOAD_AUTHORITY.json",
    "SUBSTRATE_V5_PERFORMANCE_LEDGER.json",
    "SUBSTRATE_V5_PREFLIGHT.json",
    "SUBSTRATE_V5_HAWKING_COEXISTENCE.json",
    "SUBSTRATE_V5_LOCAL_CAPABILITY_INVENTORY.json",
    "SUBSTRATE_V5_STORAGE_AND_NETWORK_PLAN.json",
    "SUBSTRATE_V5_KERNEL_CANDIDATES.json",
    "SUBSTRATE_V5_KERNEL_PARITY.json",
    "SUBSTRATE_V5_KERNEL_BENCHMARK.json",
    "SUBSTRATE_V5_KERNEL_SELECTION.json",
    "SUBSTRATE_V5_MIGRATION_AUTHORITY.json",
    "SUBSTRATE_V5_PERMANENT_STATE_SCHEMA.json",
    "SUBSTRATE_V5_ENTITY_SERVICE.json",
    "SUBSTRATE_V5_TIME_AUTHORITY.json",
    "SUBSTRATE_V5_LONG_HISTORY_POLICY.json",
    "SUBSTRATE_V5_PERSISTENCE_CANARIES.json",
    "SUBSTRATE_V5_MODEL_CONTRACT.json",
    "SUBSTRATE_V5_MODEL_REGISTRY.json",
    "SUBSTRATE_V5_MODEL_RELATIONSHIP_GRAPH.json",
    "SUBSTRATE_V5_MODEL_ROUTING.json",
    "SUBSTRATE_V5_MODEL_REPLACEMENT_CANARIES.json",
    "SUBSTRATE_V5_MODEL_TEACHING_AUTHORITY.json",
    "SUBSTRATE_V5_MODEL_SUPPORT_CATALOG.json",
    "SUBSTRATE_V5_MODEL_SUPPORT_POLICY.json",
    "SUBSTRATE_V5_MODEL_SUPPORT_CANARIES.json",
    "SUBSTRATE_V5_MODEL_SUPPORT_TRANSFER.json",
    "SUBSTRATE_V5_SENSORIUM_SCHEMA.json",
    "SUBSTRATE_V5_VIDEO_PIPELINE.json",
    "SUBSTRATE_V5_OBJECT_TRACKING.json",
    "SUBSTRATE_V5_EVENT_MODEL.json",
    "SUBSTRATE_V5_MOTION_CANARIES.json",
    "SUBSTRATE_V5_AUDIO_PIPELINE.json",
    "SUBSTRATE_V5_SPEECH_BINDING.json",
    "SUBSTRATE_V5_AUDIOVISUAL_ALIGNMENT.json",
    "SUBSTRATE_V5_AUDIO_CANARIES.json",
    "SUBSTRATE_V5_SPATIAL_SCHEMA.json",
    "SUBSTRATE_V5_3D_REPRESENTATION.json",
    "SUBSTRATE_V5_SCENE_MEMORY.json",
    "SUBSTRATE_V5_SPATIAL_CANARIES.json",
    "SUBSTRATE_V5_3D_ACTIVE_PERCEPTION.json",
    "SUBSTRATE_V5_BODY_CONTRACT.json",
    "SUBSTRATE_V5_BODY_SCHEMA.json",
    "SUBSTRATE_V5_BODY_LEARNING.json",
    "SUBSTRATE_V5_BODY_CANARIES.json",
    "SUBSTRATE_V5_ACTIVE_PERCEPTION.json",
    "SUBSTRATE_V5_ACTIVE_PERCEPTION_HEADROOM.json",
    "SUBSTRATE_V5_ACTIVE_PERCEPTION_POLICY.json",
    "SUBSTRATE_V5_ACTIVE_PERCEPTION_TRANSFER.json",
    "SUBSTRATE_V5_CROSS_MODAL_SCHEMA.json",
    "SUBSTRATE_V5_BINDING_MECHANISM.json",
    "SUBSTRATE_V5_BINDING_CANARIES.json",
    "SUBSTRATE_V5_NEGATIVE_BINDING_CONTROL.json",
    "SUBSTRATE_V5_HUMAN_TEACHING_SCHEMA.json",
    "SUBSTRATE_V5_HUMAN_INPUT_PRIVACY.json",
    "SUBSTRATE_V5_MULTIMODAL_TEACHING_CANARIES.json",
    "SUBSTRATE_V5_ADAPTATION_SCHEMA.json",
    "SUBSTRATE_V5_BACKGROUND_LEARNING.json",
    "SUBSTRATE_V5_MODEL_IMPROVEMENT.json",
    "SUBSTRATE_V5_RETENTION_AUTHORITY.json",
    "SUBSTRATE_V5_ROLLBACK_AUTHORITY.json",
    "SUBSTRATE_V5_CORPUS_CATALOG.json",
    "SUBSTRATE_V5_LICENSE_AUTHORITY.json",
    "SUBSTRATE_V5_ACQUISITION_LEDGER.json",
    "SUBSTRATE_V5_PREPROCESSING_AUTHORITY.json",
    "SUBSTRATE_V5_SPLIT_AND_LEAKAGE_AUDIT.json",
    "SUBSTRATE_V5_CHEAP_CANARIES.json",
    "SUBSTRATE_V5_CANARY_LEDGER.json",
    "SUBSTRATE_V5_CANDIDATE_LADDERS.json",
    "SUBSTRATE_V5_SELECTION_RECEIPTS.json",
    "SUBSTRATE_V5_MODERATE_PILOT.json",
    "SUBSTRATE_V5_FAILURE_MATRIX.json",
    "SUBSTRATE_V5_RESOURCE_PILOT.json",
    "SUBSTRATE_V5_DOWNLOAD_BENCHMARK.json",
    "SUBSTRATE_V5_ADMISSION.json",
    "SUBSTRATE_V5_SCIENTIFIC_CONSTITUTION.json",
    "SUBSTRATE_V5_HYPOTHESIS_GRAPH.json",
    "SUBSTRATE_V5_CLASSIFICATION_AUTHORITY.json",
    "SUBSTRATE_V5_CLAIM_BOUNDARY.json",
    "SUBSTRATE_V5_STATISTICAL_AUTHORITY.json",
    "SUBSTRATE_V5_PRINCIPAL_AUTHORITY.json",
    "SUBSTRATE_V5_PRINCIPAL_DAG.json",
    "SUBSTRATE_V5_RESOURCE_PLAN.json",
    "SUBSTRATE_V5_STOP_AND_FUTILITY.json",
    "SUBSTRATE_V5_WORKER_AUTHORITY.json",
    "SUBSTRATE_V5_INDEPENDENT_VERIFICATION.json",
    "SUBSTRATE_V5_MUTATION_REPORT.json",
    "SUBSTRATE_V5_CLEAN_CLONE.json",
    "SUBSTRATE_V5_FINAL_CLASSIFICATION.json",
    "SUBSTRATE_V5_NOUS_REVIEW_AUTHORITY.json",
    "SUBSTRATE_V5_FINAL_STATE.json",
    "SUBSTRATE_V5_TERMINAL_REPORT.md",
    "SUBSTRATE_V5_MODEL_ACQUISITION.json",
    "SUBSTRATE_V5_MODEL_RUNTIME_MATRIX.json",
    "SUBSTRATE_V5_MODEL_CONVERSION_PARITY.json",
    "SUBSTRATE_V5_MODEL_HEALTH_REPORT.json",
    "SUBSTRATE_V5_REPRESENTATIONAL_HIERARCHY.json",
    "SUBSTRATE_V5_WORKSPACE_PROJECTION.json",
    "SUBSTRATE_V5_EXPLICIT_LATENT_SYNCHRONIZATION.json",
    "SUBSTRATE_V5_REPRESENTATION_MIGRATION.json",
    "SUBSTRATE_V5_SENSOR_FUSION.json",
    "SUBSTRATE_V5_MULTIMODAL_CONFLICT.json",
    "SUBSTRATE_V5_FUSION_CANARIES.json",
    "SUBSTRATE_V5_CURRICULUM_AUTHORITY.json",
    "SUBSTRATE_V5_CURRICULUM_CONTROLS.json",
    "SUBSTRATE_V5_CURRICULUM_CANARIES.json",
    "SUBSTRATE_V5_ENVIRONMENT_CATALOG.json",
    "SUBSTRATE_V5_ENVIRONMENT_CONTRACT.json",
    "SUBSTRATE_V5_SIMULATOR_VALIDATION.json",
    "SUBSTRATE_V5_SERVICE_LIFECYCLE.json",
    "SUBSTRATE_V5_HEALTH_MODEL.json",
    "SUBSTRATE_V5_STATE_MIGRATION.json",
    "SUBSTRATE_V5_DISASTER_RECOVERY.json",
    "SUBSTRATE_V5_PRIVACY_AUTHORITY.json",
    "SUBSTRATE_V5_CONSENT_AUTHORITY.json",
    "SUBSTRATE_V5_HUMAN_DATA_RETENTION.json",
    "SUBSTRATE_V5_OPTIMIZATION_DECISIONS.json",
    "SUBSTRATE_V5_FAILURE_CLASSIFICATION.json",
    "SUBSTRATE_V5_COMPLETION_SCORECARD.json",
)


def configuration() -> dict:
    """Return a JSON-safe copy of the complete frozen v5 configuration."""

    body = {
        "implementation_branch": IMPLEMENTATION_BRANCH,
        "master_plan_sha256": MASTER_PLAN_SHA256,
        "execution_brief_sha256": EXECUTION_BRIEF_SHA256,
        "tags": {"pre": PRE_TAG, "ready": READY_TAG, "terminal": TERMINAL_TAG},
        "prior_tags": list(PRIOR_TAGS),
        "prior_classifications": PRIOR_CLASSIFICATIONS,
        "classifications": list(CLASSIFICATIONS),
        "claim_boundary": CLAIM_BOUNDARY,
        "hypotheses": HYPOTHESES,
        "phases": list(PHASES),
        "arms": list(ARMS),
        "modalities": list(MODALITIES),
        "model_roles": list(MODEL_ROLES),
        "model_independence_required": True,
        "canaries": CANARY_REQUIREMENTS,
        "candidate_ladders": {name: list(values) for name, values in CANDIDATE_LADDERS.items()},
        "statistics": STATISTICS,
        "principal_bounds": PRINCIPAL_BOUNDS,
        "activation": False,
    }
    encoded = json.dumps(body, sort_keys=True, separators=(",", ":"), default=str).encode()
    body["configuration_digest"] = hashlib.sha256(encoded).hexdigest()
    return body
